blueprint:
  name: Boost Heating
  description: Boosts heating of an area by a configurable temperature/time
  domain: automation
  input:
    thermostat:
      name: Thermostat
      description: The thermostat to adjust
      selector:
        entity:
          filter:
            domain: climate
          multiple: false
    boost_button:
      name: Boost Button
      description: The button to toggle boost heating
      selector:
        entity:
          filter:
            domain: input_boolean
          multiple: false
    boost_time:
      name: Boost Time
      description: The amount of time to boost the heating
      default: 30
      selector:
        number:
          min: 5.0
          max: 120.0
          step: 5.0
          mode: slider
          unit_of_measurement: "min"
    boost_target:
      name: Boost Target
      description: The amount to increase the thermostat target temperature
      default: 5
      selector:
        number:
          min: 1.0
          max: 10.0
          step: 1.0
          mode: slider
          unit_of_measurement: "°"
    schedules:
      name: Heating Schedules
      description: The heating schedules to be controlled
      selector:
        entity:
          filter:
            domain: switch
            integration: scheduler
          multiple: true
  source_url: https://github.com/martinpnewman/home-assistant-blueprints/blob/main/boost_heating.yaml
mode: restart
variables:
  thermostat: !input thermostat
  boost_button: !input boost_button
  boost_time: !input boost_time
  boost_target: !input boost_target
  schedules: !input schedules
triggers:
  - trigger: state
    entity_id: !input boost_button
    to: null
    from: null
conditions: []
actions:
  - if:
      - condition: state
        entity_id: !input boost_button
        state: "on"
    then:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: !input schedules
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: >-
            {{ 5 | float(0) + state_attr(thermostat, 'current_temperature') | float(0) }}
        target:
          entity_id: !input thermostat
      - delay:
          hours: 0
          minutes: 30
          seconds: 0
          milliseconds: 0
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: !input boost_button
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: !input schedules
